name: CsvWeb Build and Test

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
      
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Restore Packages
      run: dotnet restore src/DataDock.CsvWeb.sln
      
    - name: Build
      run: dotnet build -c Release src/DataDock.CsvWeb.sln
        
    - name: Test
      run: dotnet test -c Release --filter "Category!=explicit" src/DataDock.CsvWeb.Tests 
      
